Whisky-App/Whisky

README.md
=> Add discord invite link

README.md
Can also happen with other programs such as notepad. Easier to understand that this also solves the problems of other programs.
=> Update README from Steam to Whisky.md

Whisky.xcodeproj/project.pbxproj, Whisky/Utils/Logger.swift, Whisky/Utils/Wine.swift, Whisky/Views/WhiskyApp.swift, Whisky/en.lproj/Localizable.strings
1. Write Wine process output stream to console as it happens instead of all at once when the process ends
2. Create log files in `~/Library/Logs` with name in ISO 8601 format for each Wine process and sends messages to OSLog
=> Logging Fixes

Whisky.xcodeproj/project.pbxproj, Whisky/de.lproj/Localizable.strings
=> Add German localization

Whisky.xcodeproj/project.pbxproj, Whisky/uk.lproj/Localizable.strings
This PR adds Ukrainian language `Whisky/uk.lproj/Localizable.strings`
=> Add Ukrainian localization

Whisky.xcodeproj/project.pbxproj, Whisky/ko.lproj/Localizable.strings
=> Add Korean localization

README.md
The previous link had multiple files
=> Use game-porting-toolkit link from https://github.com/apple/homebrew-apple/commit/ba912ec2d9b6ec5e1eb8b0a09a143a3ed6e39c23

Whisky/Utils/Wine.swift, Whisky/Views/Bottle Views/ConfigView.swift, Whisky/en.lproj/Localizable.strings
As the title says. A toggle for the 2x Retina scaling mode
=> feat: toggle for retina (2x) mode

Whisky/Info.plist, Whisky/Utils/WineInstaller.swift, Whisky/Views/ContentView.swift
(so you don't have to manually nuke it)
=> feat: automatically update Wine when Whisky build no. changes

.github/ISSUE_TEMPLATE/bug.yml
since pre-0.3.1 fixed GPTK installation
=> change issue tracker cutoff to 0.3.1

Whisky/Models/Bottle.swift, Whisky/View Models/BottleVM.swift, Whisky/Views/BottleCreationView.swift, Whisky/Views/ContentView.swift
This sorts the in-creation bottles together with the other bottles, automatically scrolls to the correct position and selects it.
https://github.com/IsaacMarovitz/Whisky/assets/5073663/86165797-7040-4dce-a3f6-97475e1ccd93
The bottle is grayed out while in progress. You can select and open the detail view, but it will be grayed out until it finishes being creating.
https://github.com/IsaacMarovitz/Whisky/assets/5073663/a709914a-830d-4c9e-882d-b305133ec6bd
=> Scroll to the newly created bottle

README.md
I believe it's not a homebrew formula but rather a homebrew cask, kinda confusing
https://formulae.brew.sh/cask/whisky
=> Homebrew cask typo

Whisky/Views/WhiskyApp.swift, Whisky/en.lproj/Localizable.strings
=> feat: Allow the user to clear the MetalD3D shader cache

Whisky/Utils/Winetricks.swift
=> feat: support winetricks in intel macbook

Whisky/Utils/GPTK.swift
Superseeds #322 with checks to maintain back compat
=> Path fixes for GPTK 1b4

Whisky/Localizable.xcstrings
Update Localizable.xstrings for the the German language
Before the Localizable.xstrings update:
=> Update Localizable.xstrings (German)

Whisky.xcodeproj/project.pbxproj, Whisky/Localizable.xcstrings, Whisky/Utils/Logger.swift, Whisky/Views/Bottle Views/BottleView.swift, Whisky/Views/Bottle Views/ConfigView.swift, Whisky/Views/ProgramView.swift, WhiskyCmd/Main.swift, WhiskyKit/Sources/WhiskyKit/Extensions/Bundle+Extensions.swift, WhiskyKit/Sources/WhiskyKit/Extensions/Logger+Extensions.swift, WhiskyKit/Sources/WhiskyKit/Extensions/URLExtensions.swift, WhiskyKit/Sources/WhiskyKit/GPTK/GPTKInstaller.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Bottle.swift, WhiskyKit/Sources/WhiskyKit/Whisky/BottleData.swift, WhiskyKit/Sources/WhiskyKit/Whisky/BottleSettings.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Program.swift, WhiskyKit/Sources/WhiskyKit/Whisky/ProgramSettings.swift
Settings have been a little bit wonky. Things like environments were not updating properly. In addition build number would randomly clear. I hope to address all those issues in this PR. So far everything looks good according to my tests and removed a bunch of code that wasn't really needed. (less code added than removed)
The UI also changed just slightly. I only knew once looking at the code that you have to select an environment to delete it. It wasn't obvious because you have to click outside the text fields.
=> Fix sync issues with settings

Whisky.xcodeproj/project.pbxproj, Whisky/Views/Programs/EnvironmentArgView.swift, Whisky/Views/Programs/ProgramView.swift
=> Better Environemnt Args Editor

Whisky.xcodeproj/project.pbxproj, Whisky/Localizable.xcstrings, Whisky/Models/Program.swift, Whisky/Views/Bottle/BottleView.swift, Whisky/Views/Bottle/ConfigView.swift, Whisky/Views/Bottle/Pins/PinsView.swift, Whisky/Views/ContentView.swift, Whisky/Views/Programs/ProgramMenuView.swift, Whisky/Views/Programs/ProgramsView.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Bottle.swift, WhiskyKit/Sources/WhiskyKit/Whisky/BottleSettings.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Program.swift
* Added search to programs
* Added some nicer menu options to programs
* Use `ObservedObject` instead of `Binding` for classes which helps avoid using toggles to update UI
* Fixed additional sync issues with wine settings
Generally better to use `ObservedObject` instead of `Binding` for classes
=> Add more settings improvements

Whisky/Localizable.xcstrings
Some of these were already marked as translated but were not, might be worth looking into
=> Update Localizable.xcstrings (French)

Whisky/Localizable.xcstrings, Whisky/Utils/Winetricks.swift, Whisky/Views/Bottle/BottleView.swift
Canned and no longer pose a arbitrary code exec. vuln
=> feat: New Winetricks UX

Whisky/Localizable.xcstrings
This PR mostly fixes orthographic mistakes, and improves the clarity of some strings by using better suited words.
=> Fix/Improve French strings

Whisky/Localizable.xcstrings
=> French locale changes

Whisky/Localizable.xcstrings
I missed to check all strings properly before, my bad.
=> Sync Polish locales with 2.2.x release.

WhiskyKit/Sources/WhiskyKit/Extensions/Process+Extensions.swift
Made a small mistake (with big consequences) on my previous PR
=> Fix logging

Whisky.xcodeproj/project.pbxproj, Whisky/Views/Bottle/Pins/PinView.swift
Allows the user to right click a pinned program and click "Show in finder" to quickly open the location of the program's executable.
=> Adds a "Show in Finder" button to pinned program's context menus.

Whisky/Localizable.xcstrings
Pulled up the number of translated lines to 100%
=> Update Russian locale

Whisky.xcodeproj/project.pbxproj, Whisky/Localizable.xcstrings, Whisky/Views/Bottle/BottleView.swift, Whisky/Views/Bottle/RunningProcessesView.swift
As the title says. Here is a demonstration
=> feat: basic process management

WhiskyKit/Sources/WhiskyKit/Wine/Wine.swift
Fix typo in backend of the word registry
=> Update Wine.swift (typo fix)

WhiskyKit/Sources/WhiskyKit/Extensions/Program+Extensions.swift, WhiskyKit/Sources/WhiskyKit/Wine/Wine.swift
fix terminal command generation, before it would just try to run the bottle directory on wine instead of an actual executable.
=> fix terminal command generation

Whisky/Views/Bottle/Pins/PinCreationView.swift
| Before | After |
|--------|--------|
|![before](https://github.com/Whisky-App/Whisky/assets/6960799/e169745a-11cf-47ed-8c08-31f3c2ba5d96)|![after](https://github.com/Whisky-App/Whisky/assets/6960799/6d647b57-b920-4097-861d-109e81ecfbf8)|
=> Fix size of pin creation view

Whisky/Utils/Winetricks.swift, Whisky/Views/Programs/ProgramView.swift, Whisky/Views/WhiskyApp.swift, WhiskyKit/Sources/WhiskyKit/Extensions/Process+Extensions.swift, WhiskyKit/Sources/WhiskyKit/PE/Section.swift, WhiskyKit/Sources/WhiskyKit/Tar.swift
This is a quick fix for issue #1343.
* Fixes App Freeze on Program Configuration view by reimplemented `.toolbar` method 
* Adapted to new SwiftLint rules
=> Bug Fix: Program Configuration View Freezes
