.gitignore, Whisky.xcodeproj/project.pbxproj, Whisky/AppDelegate.swift, Whisky/Utils/GPT.swift, Whisky/Views/AppDelegate.swift, Whisky/Views/GPTInstallView.swift, Whisky/Views/WhiskyApp.swift, Whisky/en.lproj/Localizable.strings
There are a few issues when opening the app from the folder it has been downloaded to, e.g. ~/Downloads
1. Sparkle cannot update the application if it is launched from the folder where it has been downloaded.
2. Dropping the .dmg file into the drop area has no effect if the app is not in the Applications folder. (This fixes issue #25.)
To address this issue, I have implemented a gentle alert for the user upon the first app launch, advising them to move the application to the Applications folder. This solution works seamlessly, and the user does not need to restart the application after clicking "Move to Applications" button.
=> feat: move to applications alert on first launch

Whisky.xcodeproj/project.pbxproj, Whisky/Views/AppDBView.swift, Whisky/Views/Bottle Views/ConfigView.swift, Whisky/Views/ProgramView.swift
Fixes #29, unsure if it still works on macOS 14
=> macOS 13.3 support

Whisky/Models/Program.swift, Whisky/Views/Bottle Views/BottleView.swift, Whisky/Views/Bottle Views/InfoView.swift, Whisky/Views/Bottle Views/ProgramsView.swift, Whisky/Views/BottleRenameView.swift, Whisky/Views/ContentView.swift, Whisky/Views/ProgramView.swift
As discussed on Discord, I've removed a bunch of instances where `@State` or `@Binding` was used, but was not necessary.
=> Remove `@State` and `@Binding` where not needed

Whisky.xcodeproj/project.pbxproj, Whisky/nl.lproj/Localizable.strings
=> Add Dutch localization

Whisky/Views/Bottle Views/BottleView.swift
Put the Run button at the root of the Wine bottle, making it easier to launch apps from inside the bottle if needed
=> fix: start the run dialog at the root of the bottle instead of $whatever

Whisky/Views/ContentView.swift
On the latest commit (8d463ef507b691a05795a9f6b76dd50cfc645b9a), it seems that one line got missed during the rebase.
=> Remove forgotten line

Whisky/Models/Bottle.swift, Whisky/Views/Bottle Views/BottleView.swift
Previous Behavior:
Fixed Behavior:
=> Open C Drive Directly Instead of the Previous Folder

Whisky/Models/Bottle.swift, Whisky/Views/Bottle Views/BottleView.swift
variables **cDrive** and **cDriveURL** are only used in the line under it
=> remove some single use variables

Whisky/Views/Bottle Views/BottleView.swift, Whisky/Views/Bottle Views/ProgramsView.swift
For some reason the Bottle View starred list is not updated, when you toggle favourite apps. This forcefully triggers the refresh.
Previously:
https://github.com/IsaacMarovitz/Whisky/assets/5073663/ea9b0c9d-1abd-4888-9e02-104caadafdc1
Now:
https://github.com/IsaacMarovitz/Whisky/assets/5073663/291c6168-8489-48a2-b4cf-7504df3d2b9c
=> Trigger starred programs refresh on the main bottle view

Whisky/View Models/BottleVM.swift, Whisky/Views/WhiskyApp.swift
Previously, if the bottle directory was moved/removed, the plist wasn't updated respectively. This checks if the bottle is valid, meaning if it exists and has a valid `Metadata.plist` file. Additionally, it allows importing legacy bottles.
Hopefully, this also fixes #255.
=> Revamp bottle loading and add bottle validation

Whisky/Models/ProgramSettings.swift, Whisky/View Models/BottleVM.swift
It seems that the [URL.path](https://developer.apple.com/documentation/foundation/url/1779812-path) attribute will be deprecated, and instead should be replaced by` URL.path(percentEncoded: false)`
This also fixes #287
=> Replace deprecated path attribute

Whisky/Views/Bottle Views/ConfigView.swift, Whisky/en.lproj/Localizable.strings, WhiskyKit/Whisky/BottleSettings.swift
Adds a toggle that enables DXVK Async (by setting DXVK_ASYNC=1) in the bottle settings. Default is `true`.
Preview of toggle:
=> DXVK Async Toggle

Whisky/Assets.xcassets/AccentColor.colorset/Contents.json
An orange accent color would fit better with the app icon and general theme of Whisky.
Preview:
=> Change Accent Color to Orange

Whisky/View Models/BottleVM.swift, Whisky/Views/Bottle Views/BottleView.swift, Whisky/Views/ContentView.swift, Whisky/da.lproj/Localizable.strings, Whisky/de.lproj/Localizable.strings, Whisky/en.lproj/Localizable.strings, Whisky/es.lproj/Localizable.strings, Whisky/fi.lproj/Localizable.strings, Whisky/fr.lproj/Localizable.strings, Whisky/it.lproj/Localizable.strings, Whisky/ja.lproj/Localizable.strings, Whisky/ko.lproj/Localizable.strings, Whisky/nl.lproj/Localizable.strings, Whisky/pl.lproj/Localizable.strings, Whisky/pt-BR.lproj/Localizable.strings, Whisky/pt-PT.lproj/Localizable.strings, Whisky/ru.lproj/Localizable.strings, Whisky/tr.lproj/Localizable.strings, Whisky/uk.lproj/Localizable.strings, Whisky/vi.lproj/Localizable.strings, Whisky/zh-Hans.lproj/Localizable.strings, Whisky/zh-Hant.lproj/Localizable.strings, WhiskyKit/Whisky/Bottle.swift, WhiskyKit/Whisky/BottleData.swift
This version of Whisky does not forget bottles, that are currently unavailable (existing on disconnected hard drive for example)
Instead it shows them as unavailable, and does not allow to interact with them (deleting them from app database is an possible)
When bottles get available again (hard drive plugged back for example) it is needed to hit the refresh button, and bottle state will be refreshed in the app
=> Fix external drive problem (#449)

WhiskyKit/Sources/WhiskyKit/Whisky/BottleSettings.swift
Nice you added the esync option!
But it looks like you're setting `WINEMSYNC` instead of `WINEESYNC` when setting the esync option. I figured this is probably a mistake.
Also as just a Note: Could just use `wineEnv["WINEESYNC"] = 1` instead of the `updateValue` if you don't need to know the original value.
=> Fix esync Setting

Whisky/Localizable.xcstrings
Note: As localization for full name of ESync doesn't exists i've replaced it with `Syncing type` as it's just a section where user switches between `ESync` or `MSync` so it sounds more suiting, lemme know if it should be left as default.
=> Update polish locales with missing settings strings.

Whisky/Models/Bottle.swift, Whisky/Views/Bottle/BottleView.swift, Whisky/Views/Bottle/Pins/PinsView.swift, Whisky/Views/ContentView.swift, WhiskyKit/Sources/WhiskyKit/PE/ShellLink.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Bottle.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Program.swift
Just some program maintenance
1. Remove pins for programs that are deleted so they don't necessarily float around
2. Make `PinsView` require a program so you don't end up with empty items
3. Fix missing pins after reloading bottles
4. Overall cleanup of code
Maybe we don't want to do 1. I see a potential of adding back a deleted program and the pin is restored. Could be a useful quality of life feature.
Also, i'm not sure I understand the concept of the blocklist. It seems sort of broken right now. On launching it filters out programs but doesn't do that when you actually block a program (could be my mistake). But even if we fixed that I'm not sure what the point of the feature is.
=> Some program loading cleanup

Whisky.xcodeproj/project.pbxproj, Whisky/Localizable.xcstrings, Whisky/Models/Bottle.swift, Whisky/Views/Bottle/BottleView.swift, Whisky/Views/Bottle/Pins/PinCreationView.swift, Whisky/Views/Bottle/Pins/PinsView.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Bottle.swift
Adds UI elements for manually pinning programs, useful for built-in Windows utilities, portable applications, applications that are not installed within the `Program Files` or `Program Files (x86)` directories, applications that don't create Start Menu shortcuts, etc.
Fixes #405 
In the main Bottle view:
* Toolbar button to pin a program
* Call to action and prominent `Pin Program` button when the pinned programs list is empty
<details><summary>Manual Pinning UI and Result Examples</summary>
<p>
</p>
</details> 
<details><summary>Pinned programs are intelligently added to the Installed Programs list for configuration parity.</summary>
<p>
</p>
</details> 
<details><summary>Attempts to pin the same program multiple times are detected and disallowed.</summary>
<p>
</p>
</details>
=> [Feat] Manual Pinned Programs

Whisky/Views/Bottle/BottleCreationView.swift, Whisky/Views/Bottle/Pins/PinCreationView.swift, Whisky/Views/Bottle/WinetricksView.swift
Refactors `BottleCreationView` & `PinCreationView` to use `Form`, `toolbar` and `navigationTitle` instead of wrapped `VStack`s. Should look a bit cleaner and more consistent with general macOS UI and allow easier additions to the views in the future.
New Bottle
Pin Program
=> Update UI: BottleCreationView & PinCreationView

Whisky/Views/FileOpenView.swift
Add file name to the title when directly opening executable.
=> Fix run title localisation format

Whisky/AppDelegate.swift, Whisky/Views/FileOpenView.swift
Fixes bug where opening a file that launches Whisky does not call the `onOpenURL` handler, thus not showing the `FileOpenView` sheet.
Also fixes another bug where Whisky will crash due to bottles loading slower than `FileOpenView` appearing.
=> Fix opening through document type

Whisky/Extensions/Bottle+Extensions.swift, Whisky/Localizable.xcstrings, Whisky/Views/Bottle/BottleView.swift, Whisky/Views/FileOpenView.swift, WhiskyCmd/Main.swift, WhiskyKit/Sources/WhiskyKit/Wine/Wine.swift
Adds a button that opens a Terminal window with the correct environment variables and aliases for the current bottle.
It works by using an AppleScript to open a shell with ``eval "$(whisky shellenv "<bottle>")"`` (which can also be used on its own if Whisky CLI is installed).
=> Bottle Terminal button

Whisky.xcodeproj/project.pbxproj, Whisky/Views/Bottle/BottleCreationView.swift, Whisky/Views/Bottle/Pins/PinCreationView.swift, Whisky/Views/Common/ActionView.swift, Whisky/Views/Settings/SettingsView.swift
Slightly changed UI of the settings, pin and bottle creation views to better match macOS design, using the 'System Preferences' Bluetooth screen as a guide. Refactored the changed elements into separate view to reduce code duplication.
| Before | After |
|--------|--------|
| ![pin 0](https://github.com/Whisky-App/Whisky/assets/6960799/6840ea75-f14d-4481-a4fc-7f0d28ebc873) | ![pin 1](https://github.com/Whisky-App/Whisky/assets/6960799/5db22754-fe76-496f-9b23-49474f236dd3) |
=> Improve UI

Whisky/Localizable.xcstrings, Whisky/Views/Bottle/ConfigView.swift, WhiskyKit/Sources/WhiskyKit/Whisky/BottleSettings.swift
Apple: We add a feature!
Also Apple: We also make it 10 layers deep inside the Rosetta 2 binary locked behind an environment variable, good luck!
(Although I think some people found out that AVX support may be incomplete)
=> feat: avx feature switch

Whisky/Views/Bottle/Pins/PinView.swift, Whisky/Views/Programs/ProgramsView.swift, WhiskyKit/Sources/WhiskyKit/Whisky/Bottle.swift, WhiskyKit/Sources/WhiskyKit/Whisky/BottleSettings.swift
This adds a property to bottle pins that notes whether or not a pinned program is on an internal drive. If not, it is "removable," such that if the drive is removed, the program will not display in the Bottle Pins or Installed Programs list, but is still read from and written to the metadata plist as if it still exists. If I've covered all my bases, the user should not be able to see or interact with any hidden programs. When Whisky is next opened or refreshed when the drive is plugged in, the programs will show again. If the drive is mounted but the program is not found, it is removed like usual.
This should build on #455, except in this case a Bottle can be on an internal drive and pin programs on external ones.
=> Retain Pinned Programs on External Volumes
